### ISSUE TITLE
Error callback fires too early

### ISSUE THREAD

**Issue by 3bl3gamer** [grncdr/node-any-db-transaction#14]
Steps to reproduce:
1. Create a transaction with `autoRollback: true`.
2. Inside the transaction, call `query()` with some incorrect SQL statement and error callback.
3. When the error callback is called, `ROLLBACK` is not yet executed.
4. If you reuse the connection at this exact moment, next query will still be executed inside this failed transaction, which is not fun at all.

In PostgreSQL, for example, second query will fail:

``` js
var db = require('any-db').createConnection('postgres://somewhere')
var transaction = require('any-db-transaction')
var tx = transaction(db, {autoRollback: true})

tx.query('select error', function(err, res){
  console.log(err, res) //Error: column "error" does not exist

  // tx is NOT yet rolled back
  db.query('select 2', function(err, res){
    console.log(err, res) //Error: current transaction is aborted, commands ignored
  })
})
```

**Comment by grncdr** [comment]
I'm not sure what the issue is... are you expecting the second query to succeed?
