### ISSUE TITLE
Retry on serialization failures

### ISSUE THREAD

**Issue by markusmalkusch** [grncdr/node-any-db-transaction#15]
Your library does by default rollback transactions on errors. This is not a desired behaviour for [serialization failures in Postgres](https://www.postgresql.org/docs/current/static/transaction-iso.html):

> Applications using this level must be prepared to retry transactions due to serialization failures.

[MySQL has similar recommendations](http://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html):

> Always be prepared to re-issue a transaction if it fails due to deadlock. Deadlocks are not dangerous. Just try again. 

From your documentation I couldn't read how to achieve this behaviour. Does your library support such retry behaviour? If not, would you mind adding this?

**Comment by grncdr** [comment]
Hi @markusmalkusch, I don't think there's a sensible way for this library to retry transactions for you, as it's not something the databases themselves support. (There is no "retry transaction" SQL statement I'm aware of).

My reading of the docs above is "restart the processing that failed the transaction". IMO this should be handled by the application creating the transaction, but if there's a generalized way to handle it I'd be interested to hear more.

**Comment by malkusch** [comment]
The client has to retry. I.e. the complete unit of work which is encapsulated in the transaction should be replayed. Your library is the perfect place for implementing this. I'm out of Javascript land, but the general idea would be in Pseudo Code:

     yourlibrary.enableRetry(3); // While it's actually a better idea to have it enabled per default
    yourlibrary.withinTransaction(unitOfWork); // unitOfWork is a callback which contains all the transaction's SQL statements; withinTransaction() does the commit, rollback and retry magic.
